ALTER TABLE Students ADD COLUMN middleName VARCHAR(45);

ALTER TABLE Books ADD COLUMN genre VARCHAR(45);

ALTER TABLE Cars ADD COLUMN color VARCHAR(45);

ALTER TABLE Laptops MODIFY COLUMN purchaseDate DATE NOT NULL;

ALTER TABLE Books MODIFY COLUMN publicationYear INT NOT NULL;
